<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <title>Crypt-Kicker</title>
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="@mbonell">

    <!-- Le styles -->
    <link href="themes/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="themes/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet">
    <link rel="stylesheet" href="themes/css/styles.css">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>                                                                                      
    <![endif]-->

      </head>
  <body> 
  <div id='wrap'>
   <header class='heady'>
	<div class="container">
		<img src='http://cdn1.iconfinder.com/data/icons/juicyfruit_by_salleedesign/128x128/key.png' class='pull-left'/>
	    <h1>Crypt-Kicker</h1>
	</div>
</header>
	 
		<!-- container -->
    <div class="container">
    	<?php if( $error ) { ?>
    	<div style='height:5px;'></div>
	<div class="alert alert-error">
	  <button type="button" class="close" data-dismiss="alert">&times;</button>
  	  <strong>Error: </strong> <?php echo $error?>
	</div>
	<?php } ?>
    	<div style='height:50px;'></div>
<form class="form-signin <?php if($output){ ?> pull-left <?php }?>" method="post">
	<form action="" method="post" id="formDecrypt">
	<label for='txtKey'>Key:</label>
	<input id='txtKey' name='txtKey' type='text' class='input-block-level' value='<?php echo $key;?>'>
	<label for='txtInput'>Input:</label>
	<textarea id="txtInput" name="txtInput" rows="10" cols="60" class="input-block-level"><?php echo $input;?></textarea>
	<input type="submit" value="Decrypt" name="btnDecrypt" id="btnDecrypt" class="btn btn-large btn-primary" />
</form>
<?php if($output){ ?>
<img src='http://cdn1.iconfinder.com/data/icons/customicondesignoffice5/128/navigate-right.png' class='pull-left mg' />
<div id="output" class='form-signin pull-left'>
    Key:
    <pre><?php echo $crypted_key;?></pre>
	Output:
	<pre><?php echo $output;?></pre>
</div> 
<?php } ?>
    </div> 
    <!-- /container -->
    
     </div>
	<footer class="footer">
	      <div class="container">
	        <p class="pull-right"><a href="#">Ir arriba</a></p>
	        <p><em>By: Marcela Bonell.</em> <i class="icon-heart"></i> </p>
	        <ul class="footer-links">
	          <li><a href="http://twitter.com/mbonell">Follow me</a></li>
	        </ul>
	      </div>
	</footer>
    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
  	<script type="text/javascript" src="themes/bootstrap/js/bootstrap.min.js"></script>
  	
	</body>
</html>