<!DOCTYPE html>
<html>
  	<head>
    	<meta charset="utf-8">
    	<title>Crypt Kicker</title>
    	<link rel="stylesheet" href="themes/css/styles.css">
	</head>
<body>
	<div>
		<h1>Crypt Kicker</h1>
		<form action="" method="post" id="formDecrypt">
	        <div>
	        	<div><label>Input:</label></div>
				<textarea id="txtInput" name="txtInput" rows="10" cols="60" style="resize:none;"><?php echo $input;?></textarea>
				<div><input type="submit" value="Decrypt" name="btnDecrypt" id="btnDecrypt" /></div>
	        </div>
	        <div id="error"><?php if($error) echo "Error: {$error}";?></div>
	       	<div id="output">
	       	<?php if($output){ ?>
	        	<label>Output:</label>
	          	<div id="textDecrypt"><?php echo $output;?></div>
	        <?php } ?>
	        </div>  
	    </form>
	    <div id="autor">By: Marcela Bonell.</div>
	</div>
</body>
</html>